### ISSUE TITLE
Template for whitelisting selected IAM roles

### ISSUE THREAD

**Issue by marcin-kolda** [forseti-security/policy-library#115]
We would like to have a template which allows only selected roles for given users. All other IAM bindings should be reported as violations. So instead of blacklisting all other roles, we would like to whitelist only few of them.

Example:
```yaml
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedRolesConstraintV1
metadata:
  name: whitelist_roles
  annotations:
    description: Only test.com groups can have appengine.appViewer and logging.viewer roles. All others bindings are not allowed.
spec:
  severity: high
  match:
    target: ["organization/*"]
    exclude: [] # optional, default is no exclusions
  parameters:
    role:
    - roles/appengine.appViewer
    - roles/logging.viewer
    members:
    - "group:*@test.com"
```

**Comment by morgante** [comment]
Have you looked at the https://github.com/forseti-security/policy-library/blob/master/samples/iam_restrict_role.yaml constraint? It seems like it should solve this use case.

**Comment by marcin-kolda** [comment]
Hi @morgante, unfortunately iam_restrict_role.yaml doesn't work for me (see #117). As I understand it validates the minimum required roles (e.g. all project require project viewer role) in whitelisting mode.
In my use case I'd like to define possible roles which can be used in IAMs for given members, e.g. few read roles for users, deploy roles for service accounts. All other IAM bindings should be reported as violations.

**Comment by marcin-kolda** [comment]
After clarification in #117 the iam_restrict_role.yaml rule still will not work in my case.

I would like to whitelist specific roles and blacklist everything else. I don't want to specify all possible roles for blacklisting, as new one are added dynamically. I'd like to define few roles as whitelisted, which were evaluated and approved. Everything else should be marked as violation.

To give you more context, we want to use Terraform Validator to validate other teams IAM changes in our CI pipeline. So we might end up using different rules for different access on the same project, e.g. service accounts for deploy, user account for read only.

We could also use combination of 2 rules:
- multiple existing iam_restrict_role.yaml rules in whitelisting mode for every approved role,
- new rule, which would use the same allowed roles and blacklist every other role

**Comment by morgante** [comment]
Thanks for clarifying, I would suggest solving this through a combination of a few constraint:
1. A whitelist (using `iam_restrict_role`) of approved members for those each approved role
2. A new constraint template to whitelist only the approved roles (and block any other role)

(1) can be done out fo the box today. (2) would require that you update the [constraint template](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_iam_allowed_bindings_v1.yaml) slightly to match your use case.

**Comment by FanchenBao** [comment]
I agree with morgante. Use `iam_restrict_role` constraint for **each** whitelisted role. They can detect any member that is not allowed to have such roles. Then you can either modify an existing template to whitelist the given roles, or you can write the template yourself. For example, the rego code for the template can be like this:
```rego
package templates.gcp.GCPIAMWhitelistRolesConstraintV1
            
import data.validator.gcp.lib as lib

deny[{
    "msg": message,
    "details": metadata,
}] {
    constraint := input.constraint
    lib.get_constraint_params(constraint, params)
    asset := input.asset

    binding := asset.iam_policy.bindings[_]
    role := binding.role

    whitelist := lib.get_default(params, "whitelist_roles", [])
    whitelist_set := {ele | ele := whitelist}

    not whitelist_set[role]

    message := sprintf("IAM policy for %v does not allow role %v", [asset.name, role])

    metadata := {
        "resource": asset.name,
        "role": role,
    }
}
```
And the constraint can be like this:
```yaml
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMWhitelistRolesConstraintV1
metadata:
  name: whitelist_roles
  annotations:
    description: Only the roles in this whitelist can be allowed
spec:
  severity: high
  match:
    target: ["organization/*"]
    exclude: [] # optional, default is no exclusions
  parameters:
    whitelist_roles:
    - "roles/appengine.appViewer"
    - "roles/logging.viewer"
```
