### ISSUE TITLE
iam_restrict_role rule in whitelisting mode doesn't work

### ISSUE THREAD

**Issue by marcin-kolda** [forseti-security/policy-library#117]
I'm trying to use [iam_restrict_role](https://github.com/forseti-security/policy-library/blob/master/samples/iam_restrict_role.yaml) in whitelisting mode, but it doesn't generate any violations.

Here's my rule config:
```yaml
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedBindingsConstraintV1
metadata:
  name: whitelist_viewer_role
  annotations:
    description: All projects must have viewer
spec:
  severity: high
  match:
    target: ["organization/*"]
    exclude: [] # optional, default is no exclusions
  parameters:
    mode: whitelist
    role: roles/viewer
    members:
    - "*"

```
Terraform config file:
```yaml
provider "google" {
  version = "~> 2"
  project = "project-id"
}

resource "google_project_iam_member" "project" {
  project = "project-id"
  role    = "roles/editor"
  member  = "user:name.surname@example.com"
}
```
GCP project id which I'm using doesn't have any Viewer configured. As I understand I should get violation because there is no any `viewer` role configured on my project. Is my understanding correct?

I'm using the following versions:
```
Terraform v0.11.14
+ provider.google v2.10.0
```
and Terraform validator in version: `Build version: 2019-06-19`
