### ISSUE TITLE
Compute Zone Not Violating

### ISSUE THREAD

**Issue by jdyke** [forseti-security/policy-library#121]
Afternoon,

I am working on the compute engine zone constraint and have tried denylist and allowlist.

constraint:

```
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPComputeZoneConstraintV1
metadata:
  name: compute_zone_denylist_one
spec:
  severity: high
  match:
    target: ["organization/*"]
  parameters:
    mode: "denylist"
    zones:
      - asia-east1-b
    exemptions: []
```

tf code:

```
variable project {}

provider "google" {
  project = "${var.project}"
  region = "asia-east1"
}

resource "google_compute_instance" "common" {
    name         = "test-instance"
    machine_type = "n1-standard-1"
    zone = "asia-east1-b"

    boot_disk {
      initialize_params {
        image = "debian-cloud/debian-9"
      }
    }

    network_interface {
      network = "default"
    }
}
```

template is gcp_compute_zone_v1.yaml

Any insight into why this might not be marking as violation?
