### ISSUE TITLE
Match/Exclude options are not effective

### ISSUE THREAD

**Issue by yunus** [forseti-security/policy-library#219]
When I try to use match/exclude options with scorecard (make audit), they are not taken into consideration. When I check the config [validator code](https://github.com/forseti-security/config-validator/blob/master/pkg/gcv/cf/audit.go), I see that match and exclude logic is there.
Is it possible that policy library downloads an old version of the scorecard (0.2.0)?

### How to reproduce
I've tested the match feature with CMEK rule, see below. I try to scope it to only a project instead of the whole organization. I've added the project with number as a target and ran `make audit`
I don't see any errors although there supposed to be some.

```yaml
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPStorageCMEKEncryptionConstraintV1
metadata:
  name: storage_cmek_encryption
spec:
  severity: high
  match:
    gcp:
      target: ["project/12345"]
  parameters: {}
```

I have tried other combinations: 

- target: ["project/*"] -> returns all the buckets that do not have cmek, so it works
- replaced _project_ with _projects_ -> still no change, I don't see any 
- I tried also removing _gcp_ part as below, and the result is still the same, I don't see any buckets without cmek
```yaml
match:
  target: ["project/12345"]
```
