### ISSUE TITLE
Forseti Config Validator Scanner does not report firewall related violations

### ISSUE THREAD

**Issue by xingao267** [forseti-security/policy-library#301]
Policies that should report violation:

```
network_enable_firewall_logs.yaml

apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPNetworkEnableFirewallLogsConstraintV1
metadata:
  name: enable-network-firewall-logs
  annotations:
    description: Ensure Firewall logs is enabled for every firewall in VPC Network
spec:
  severity: high
  match:
    gcp:
      target: ["organization/*"]
  parameters: {}
```

and 
```
restrict_fw_rule_world_open.yaml

apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPRestrictedFirewallRulesConstraintV1
metadata:
  name: restrict-firewall-rule-world-open
  annotations:
    bundles.validator.forsetisecurity.org/scorecard-v1: security
spec:
  severity: high
  match:
    target: ["organization/*"]
  parameters:
    rules:
      - direction: "INGRESS"
        source_ranges:
        - "0.0.0.0/0"
        enabled: "true"
        rule_type: "allowed"
```

Example TF config that is deployed:
```
resource "google_compute_firewall" "allow-all-ingress" {
  name          = "allow-all-ingress"
  project       = "corebuild-10022019"
  network       = "default"
  direction     = "INGRESS"
  source_ranges = ["0.0.0.0/0"]
  priority      = "2000"

  allow {
    protocol = "all"
  }
}
```

I tried validating the config with Terraform Validator and it works fine. Two violations are reported, one for log being disabled and one for that allow-all-ingress firewall rule is prohibited. But the violations is not reported by FCV.
