### ISSUE TITLE
Restricted Firewall Template throws error for constraints using all ports

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/policy-library#323]
## Story
If a constraint for the [restricted firewall rules template](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_restricted_firewall_rules_v1.yaml) uses the parameter `port: "all"` AND a rule is evaluated that has a port range, then a rego error is thrown:

Error:
```
validator/restricted_firewall_rules.rego:242: eval_builtin_error: 
to_number: strconv.ParseFloat: parsing "all": invalid syntax
```

Sample constraint:
```
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPRestrictedFirewallRulesConstraintV1
metadata:
  name: restrict-firewall-rule-world-open-tcp-udp-all-ports
  annotations:
    bundles.validator.forsetisecurity.org/forseti-security: v2.26.0
spec:
  severity: high
  match:
    target: ["organization/*"]
  parameters:
    rules:
      - direction: "INGRESS"
        enabled: "true"
        port: "all"
        protocol: "tcp"
        rule_type: "allowed"
        source_ranges:
        - "0.0.0.0/0"
```

Sample rule:
```
"allowed": [
                    {
                        "IPProtocol": "udp",
                        "ports": [
                          "0-65535"
                        ]
                    }
                ],
                "creationTimestamp": "2019-08-09T12:53:34.847-07:00",
                "description": "",
                "direction": "INGRESS",
                "disabled": false,
                "id": "12407153413353937",
                "logConfig": {
                    "enable": false
                },
                "name": "cf-test-fw-rule-tcp-all-port-range0",
                "network": "https://www.googleapis.com/compute/v1/projects/cf-gcp-challenge-dev/global/networks/default",
                "priority": 1000,
                "selfLink": "https://www.googleapis.com/compute/v1/projects/cf-gcp-challenge-dev/global/firewalls/cf-test-fw-rule-tcp-all-port-range0",
                "sourceRanges": [
                    "0.0.0.0/0"
                ],
```

## Proposed Solution
Update the existing template to check the ports differently to handle this case. In addition, a FW rule with port range 0-65535 or 1-65535 should be considered to be violating the sample constraint.

## Acceptance Criteria
Add tests for this scenario.
