### ISSUE TITLE
IAM Audit log policy validation seems producing false positives

### ISSUE THREAD

**Issue by xingao267** [forseti-security/policy-library#367]
I have the following constraints and CAI data

```
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAuditLogConstraintV1
metadata:
  name: iam_enable_audit_logs
spec:
  severity: high
  match:
    target:
    - "organization/12345678/*"
    - "folder/4567/*"
  parameters:
    log_types:
    - DATA_READ
    - DATA_WRITE
    - ADMIN_READ
    services:
    - allServices
```

```
{"ancestors":["folders/88888888","organizations/12345678"],"name":"//cloudresourcemanager.googleapis.com/projects/good","asset_type":"cloudresourcemanager.googleapis.com/Project","iam_policy":{"version":1,"etag":"BwWKImhngxs=","audit_configs":[{"service":"allServices","audit_log_configs":[{"log_type":1},{"log_type":2},{"log_type":3}]}]}}
```

It seems should be good and do not report violations. But when I run the CFT scorecard on those, it gives the following violation
```
Other,iam_enable_audit_logs,//cloudresourcemanager.googleapis.com/projects/good,"IAM policy for //cloudresourcemanager.googleapis.com/projects/good does not have correct audit logs enabled in service(s) [""allServices""]"
```
