### ISSUE TITLE
Severity field not taken into account in Security Command Center

### ISSUE THREAD

**Issue by krab-skunk** [forseti-security/policy-library#389]
Hi, i'm using master branch (from 2 days ago) forseti and latest docker image for Config Validator.

They work great together and find me violations but i don't see the severity field being taken into account.

Example with one simple policy:

```
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPRestrictedFirewallRulesConstraintV1
metadata:
  name: open-port-22
  annotations:
    bundles.validator.forsetisecurity.org/forseti-security: v2.26.0
    bundles.validator.forsetisecurity.org/scorecard-v1: security
    description: Checks for open firewall rules allowing port on 22 to 0.0.0.0
spec:
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - "organizations/**"
  parameters:
    rules:
    - direction: "INGRESS"
      source_ranges:
      - "0.0.0.0/0"
      port: "22"
      protocol: "tcp"
      enabled: "true"
      rule_type: "allowed"
```

The config validator detect a violation and notifier push the notification correctly to the SCC, but as you notice, **severity is set to HIGH in the policy.**
Nevertheless, in the SCC, nowhere i see the severity field, thus my issues can't be sorted by severity:/

DId i miss something, thanks a lot for your help.
